"use client";

import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from "react";

export type AppLanguage = "en" | "uz" | "ru";
export type AppTheme = "light" | "dark";

type AppPreferencesContextValue = {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  theme: AppTheme;
  setTheme: (theme: AppTheme) => void;
  toggleTheme: () => void;
  t: (key: string, params?: Record<string, string | number>) => string;
};

const STORAGE_LANGUAGE_KEY = "ts-notebook-shop-language";
const STORAGE_THEME_KEY = "ts-notebook-shop-theme";

const translations: Record<AppLanguage, Record<string, string>> = {
  en: {
    "common.language": "Language",
    "common.theme": "Theme",
    "common.light": "Light",
    "common.dark": "Dark",
    "common.english": "English",
    "common.uzbek": "Uzbek",
    "common.russian": "Russian",
    "common.home": "Home",
    "common.cart": "Cart",
    "common.checkout": "Checkout",
    "common.country": "Country",
    "common.stateProvince": "State/Province",
    "common.zipPostalCode": "Zip/Postal Code",
    "common.city": "City",
    "common.company": "Company",
    "common.phoneNumber": "Phone Number",
    "common.firstName": "First Name",
    "common.lastName": "Last Name",
    "common.emailAddress": "Email Address",
    "common.streetAddress": "Street Address",
    "common.apartmentSuite": "Apartment / Suite",
    "common.applyDiscount": "Apply Discount",
    "common.promocode": "Promocode",
    "common.applied": "Applied",
    "common.subtotal": "Subtotal",
    "common.shipping": "Shipping",
    "common.tax": "Tax",
    "common.total": "Total",
    "common.orderTotal": "Order Total",
    "common.noImage": "No image",
    "topBar.days": "Mon–Thu:",
    "topBar.hours": "9:00 AM - 5:30 PM",
    "topBar.showroom": "Visit our showroom in 1234 Street Address City Address, 1234",
    "topBar.contactUs": "Contact Us",
    "topBar.callUs": "Call Us:",
    "nav.laptops": "Laptops",
    "nav.desktopPcs": "Desktop PCs",
    "nav.networkingDevices": "Networking Devices",
    "nav.printersScanners": "Printers & Scanners",
    "nav.pcParts": "PC Parts",
    "nav.allOtherProducts": "All Other Products",
    "nav.repairs": "Repairs",
    "nav.ourDeals": "Our Deals",
    "hero.deal": "EOFY DEAL",
    "hero.title": "Score A Bonus Gaming Monitor",
    "hero.subtitle": "When you buy any selected MSI gaming desktop",
    "hero.shopNow": "SHOP NOW",
    "hero.valid": "Valid from May 12 – Sep 7, 2020 or while stocks last.",
    "hero.worthUp": "Worth Up",
    "hero.worthTo": "To $599AU",
    "hero.processor": "Intel® Core™ i9 processor",
    "newProducts.title": "New Products",
    "newProducts.seeAll": "See All New Products",
    "product.inStock": "in stock",
    "product.checkAvailability": "check availability",
    "product.reviews": "Reviews ({count})",
    "product.noProductsFound": "No products found",
    "product.supabaseEmpty": "Supabase `products` table is empty or not connected yet.",
    "category.collection": "MSI Collection",
    "category.seeAllProducts": "See All Products",
    "category.customBuilds": "Custom Builds",
    "category.preBuiltPcs": "Pre-built PCs",
    "category.miniItx": "Mini ITX",
    "category.towerCases": "Tower Cases",
    "category.msiGs": "MSI GS Series",
    "category.msiGt": "MSI GT Series",
    "category.msiGl": "MSI GL Series",
    "category.msiGe": "MSI GE Series",
    "category.gaming": "Gaming",
    "category.professional": "Professional",
    "category.curved": "Curved",
    "category.ultraWide": "UltraWide",
    "category.msiInfinite": "MSI Infinite Series",
    "category.msiTrident": "MSI Trident",
    "category.msiNightblade": "MSI Nightblade",
    "instagram.title": "Follow us on Instagram for News, Offers & More",
    "testimonial.leaveReview": "Leave Us A Review",
    "support.productSupport": "Product Support",
    "support.productSupportDesc": "Up to 3 years on-site warranty available for your peace of mind.",
    "support.personalAccount": "Personal Account",
    "support.personalAccountDesc": "With big discounts, free delivery and a dedicated support specialist.",
    "support.amazingSavings": "Amazing Savings",
    "support.amazingSavingsDesc": "Up to 70% off new Products, you can be sure of the best price.",
    "footer.newsletterTitle": "Sign Up To Our Newsletter.",
    "footer.newsletterDesc": "Be the first to hear about the latest offers.",
    "footer.yourEmail": "Your Email",
    "footer.subscribe": "Subscribe",
    "footer.information": "Information",
    "footer.address": "Address",
    "footer.addressText": "Address: 1234 Street Adress City Address, 1234",
    "footer.phones": "Phones:",
    "footer.openHours1": "We are open: Monday-Thursday: 9:00 AM - 5:30 PM",
    "footer.openHours2": "Friday: 9:00 AM - 6:00 PM",
    "footer.openHours3": "Saturday: 11:00 AM - 5:00 PM",
    "footer.email": "E-mail:",
    "footer.copyright": "Copyright © 2020 Shop Pty. Ltd.",
    "cart.shoppingCart": "Shopping Cart",
    "cart.itemsInCart": "{count} item(s) in your cart",
    "cart.continueShopping": "Continue Shopping",
    "cart.product": "Product",
    "cart.price": "Price",
    "cart.qty": "Qty",
    "cart.total": "Total",
    "cart.clear": "Clear Shopping Cart",
    "cart.update": "Update Shopping Cart",
    "cart.empty": "Your cart is empty",
    "cart.emptyDesc": "Add a product to see it here.",
    "cart.summary": "Summary",
    "cart.estimateShipping": "Estimate Shipping and Tax",
    "cart.enterDestination": "Enter your destination to get a shipping estimate.",
    "cart.applyDiscountCode": "Apply Discount Code",
    "cart.enterDiscount": "Enter discount code",
    "cart.proceedCheckout": "Proceed to Checkout",
    "cart.paypal": "Check out with PayPal",
    "cart.multipleAddresses": "Check Out with Multiple Addresses",
    "cart.usePromo": "Use promo:",
    "cart.promoInvalid": "Promo code is not valid. Try {code}.",
    "cart.promoSuccess": "{code} applied successfully. You now get 50% off your full order total.",
    "cart.discountRow": "Promo ({code})",
    "cart.addItemBeforeCheckout": "Add at least one product before checking out.",
    "cart.checkoutReady": "Your details are ready. Redirecting to checkout.",
    "cart.fillShippingFirst": "Please complete country, state/province and zip code first.",
    "cart.countryRequired": "Please choose a country.",
    "cart.stateRequired": "Please fill in State/Province.",
    "cart.stateMin": "Enter at least 2 characters.",
    "cart.zipRequired": "Zip/Postal Code is required.",
    "cart.zipInvalid": "Zip/Postal Code format is invalid.",
    "cart.discountRequired": "Please enter a discount code.",
    "cart.discountMin": "Discount code must be at least 4 characters.",
    "checkout.completeDetails": "Complete your shipping details and review your order before placing it.",
    "checkout.secure": "Secure checkout experience",
    "checkout.shippingAddress": "Shipping Address",
    "checkout.useActive": "Use your active contact details so we can reach you quickly.",
    "checkout.optional": "Optional",
    "checkout.placeOrder": "Place Order",
    "checkout.backToCart": "Back to Cart",
    "checkout.orderSummary": "Order Summary",
    "checkout.itemsSelected": "{count} item(s) selected",
    "checkout.empty": "Your cart is empty",
    "checkout.emptyDesc": "Add products to see your order summary here.",
    "checkout.confirmed": "Order confirmed",
    "checkout.confirmedDesc": "Your order has been accepted. We will contact you soon.",
    "checkout.confirmedSub": "Thank you for shopping with us. Our team will review your details and reach out shortly with the next steps.",
    "checkout.continue": "Continue",
    "checkout.keepShopping": "Keep Shopping",
    "checkout.orderReady": "Everything looks good. Your order is ready to be submitted.",
    "checkout.fillRequired": "Please complete the required fields before placing your order.",
    "checkout.cartEmptyError": "Your cart is empty. Please add products before placing an order.",
    "checkout.emailInvalid": "Please enter a valid email address.",
    "checkout.emailRequired": "Email address is required.",
    "checkout.firstNameMin": "First name must be at least 2 characters.",
    "checkout.firstNameRequired": "First name is required.",
    "checkout.lastNameMin": "Last name must be at least 2 characters.",
    "checkout.lastNameRequired": "Last name is required.",
    "checkout.streetMin": "Street address must be at least 6 characters.",
    "checkout.streetRequired": "Street address is required.",
    "checkout.cityMin": "City must be at least 2 characters.",
    "checkout.cityRequired": "City is required.",
    "checkout.stateMin": "State / Province must be at least 2 characters.",
    "checkout.stateRequired": "State / Province is required.",
    "checkout.zipInvalid": "Please enter a valid ZIP / Postal Code.",
    "checkout.zipRequired": "ZIP / Postal Code is required.",
    "checkout.countryRequired": "Country is required.",
    "checkout.phoneInvalid": "Please enter a valid phone number.",
    "checkout.phoneRequired": "Phone number is required.",
    "deals.title": "Our Deals",
    "deals.desc": "Routing is working. Add campaigns and promo cards here.",
  },
  uz: {
    "common.language": "Til",
    "common.theme": "Mavzu",
    "common.light": "Yorug‘",
    "common.dark": "Qorong‘i",
    "common.english": "English",
    "common.uzbek": "O‘zbek",
    "common.russian": "Русский",
    "common.home": "Bosh sahifa",
    "common.cart": "Savat",
    "common.checkout": "Buyurtma",
    "common.country": "Mamlakat",
    "common.stateProvince": "Viloyat/Shahar",
    "common.zipPostalCode": "Pochta indeksi",
    "common.city": "Shahar",
    "common.company": "Kompaniya",
    "common.phoneNumber": "Telefon raqami",
    "common.firstName": "Ism",
    "common.lastName": "Familiya",
    "common.emailAddress": "Email manzil",
    "common.streetAddress": "Ko‘cha manzili",
    "common.apartmentSuite": "Xonadon / Ofis",
    "common.applyDiscount": "Chegirmani qo‘llash",
    "common.promocode": "Promokod",
    "common.applied": "Qo‘llandi",
    "common.subtotal": "Oraliq summa",
    "common.shipping": "Yetkazish",
    "common.tax": "Soliq",
    "common.total": "Jami",
    "common.orderTotal": "Umumiy narx",
    "common.noImage": "Rasm yo‘q",
    "topBar.days": "Du–Pa:",
    "topBar.hours": "9:00 - 17:30",
    "topBar.showroom": "1234 Street Address City Address, 1234 dagi showroomimizga tashrif buyuring",
    "topBar.contactUs": "Bog‘lanish",
    "topBar.callUs": "Qo‘ng‘iroq qiling:",
    "nav.laptops": "Noutbuklar",
    "nav.desktopPcs": "Desktop kompyuterlar",
    "nav.networkingDevices": "Tarmoq qurilmalari",
    "nav.printersScanners": "Printer va skanerlar",
    "nav.pcParts": "Kompyuter qismlari",
    "nav.allOtherProducts": "Boshqa mahsulotlar",
    "nav.repairs": "Ta’mirlash",
    "nav.ourDeals": "Aksiyalar",
    "hero.deal": "MAXSUS AKSIYA",
    "hero.title": "Bonus gaming monitorni qo‘lga kiriting",
    "hero.subtitle": "Tanlangan MSI gaming desktop xarid qilganingizda",
    "hero.shopNow": "HOZIR XARID QILING",
    "hero.valid": "12-maydan 7-sentabrgacha yoki mahsulotlar tugaguncha amal qiladi.",
    "hero.worthUp": "Qiymati",
    "hero.worthTo": "$599AU gacha",
    "hero.processor": "Intel® Core™ i9 protsessori",
    "newProducts.title": "Yangi mahsulotlar",
    "newProducts.seeAll": "Barcha yangi mahsulotlar",
    "product.inStock": "omborda bor",
    "product.checkAvailability": "mavjudligini tekshiring",
    "product.reviews": "Sharhlar ({count})",
    "product.noProductsFound": "Mahsulot topilmadi",
    "product.supabaseEmpty": "Supabase `products` jadvali bo‘sh yoki hali ulanmagan.",
    "category.collection": "MSI kolleksiyasi",
    "category.seeAllProducts": "Barcha mahsulotlar",
    "category.customBuilds": "Maxsus yig‘malar",
    "category.preBuiltPcs": "Tayyor kompyuterlar",
    "category.miniItx": "Mini ITX",
    "category.towerCases": "Tower korpuslar",
    "category.msiGs": "MSI GS seriyasi",
    "category.msiGt": "MSI GT seriyasi",
    "category.msiGl": "MSI GL seriyasi",
    "category.msiGe": "MSI GE seriyasi",
    "category.gaming": "Gaming",
    "category.professional": "Professional",
    "category.curved": "Egri ekran",
    "category.ultraWide": "UltraWide",
    "category.msiInfinite": "MSI Infinite seriyasi",
    "category.msiTrident": "MSI Trident",
    "category.msiNightblade": "MSI Nightblade",
    "instagram.title": "Yangiliklar, takliflar va boshqalar uchun Instagram’da kuzating",
    "testimonial.leaveReview": "Sharh qoldiring",
    "support.productSupport": "Mahsulot yordami",
    "support.productSupportDesc": "Xotirjamlik uchun 3 yilgacha joyida kafolat mavjud.",
    "support.personalAccount": "Shaxsiy akkaunt",
    "support.personalAccountDesc": "Katta chegirmalar, bepul yetkazish va alohida mutaxassis yordami bilan.",
    "support.amazingSavings": "Ajoyib tejash",
    "support.amazingSavingsDesc": "Yangi mahsulotlarda 70% gacha chegirma, eng yaxshi narx kafolatlangan.",
    "footer.newsletterTitle": "Newsletterimizga yoziling.",
    "footer.newsletterDesc": "So‘nggi takliflardan birinchi bo‘lib xabardor bo‘ling.",
    "footer.yourEmail": "Emailingiz",
    "footer.subscribe": "Obuna bo‘lish",
    "footer.information": "Ma’lumot",
    "footer.address": "Manzil",
    "footer.addressText": "Manzil: 1234 Street Adress City Address, 1234",
    "footer.phones": "Telefonlar:",
    "footer.openHours1": "Ish vaqti: Dushanba-Payshanba: 9:00 - 17:30",
    "footer.openHours2": "Juma: 9:00 - 18:00",
    "footer.openHours3": "Shanba: 11:00 - 17:00",
    "footer.email": "E-mail:",
    "footer.copyright": "Copyright © 2020 Shop Pty. Ltd.",
    "cart.shoppingCart": "Savat",
    "cart.itemsInCart": "Savatda {count} ta mahsulot bor",
    "cart.continueShopping": "Xaridni davom ettirish",
    "cart.product": "Mahsulot",
    "cart.price": "Narx",
    "cart.qty": "Soni",
    "cart.total": "Jami",
    "cart.clear": "Savatni tozalash",
    "cart.update": "Savatni yangilash",
    "cart.empty": "Savatingiz bo‘sh",
    "cart.emptyDesc": "Bu yerda ko‘rish uchun mahsulot qo‘shing.",
    "cart.summary": "Hisob",
    "cart.estimateShipping": "Yetkazish va soliqni hisoblash",
    "cart.enterDestination": "Yetkazish narxini hisoblash uchun manzilingizni kiriting.",
    "cart.applyDiscountCode": "Chegirma kodini qo‘llash",
    "cart.enterDiscount": "Chegirma kodini kiriting",
    "cart.proceedCheckout": "Buyurtmaga o‘tish",
    "cart.paypal": "PayPal orqali to‘lash",
    "cart.multipleAddresses": "Bir nechta manzil bilan to‘lash",
    "cart.usePromo": "Promo kod:",
    "cart.promoInvalid": "Promo kod noto‘g‘ri. {code} ni sinab ko‘ring.",
    "cart.promoSuccess": "{code} muvaffaqiyatli qo‘llandi. Endi umumiy narxdan 50% chegirma beriladi.",
    "cart.discountRow": "Promo ({code})",
    "cart.addItemBeforeCheckout": "Checkoutdan oldin kamida bitta mahsulot qo‘shing.",
    "cart.checkoutReady": "Ma’lumotlar tayyor. Checkout sahifasiga o‘tilmoqda.",
    "cart.fillShippingFirst": "Davom etishdan oldin mamlakat, viloyat va indeksni to‘ldiring.",
    "cart.countryRequired": "Mamlakatni tanlang.",
    "cart.stateRequired": "Viloyat/Shahar maydonini to‘ldiring.",
    "cart.stateMin": "Kamida 2 ta belgi kiriting.",
    "cart.zipRequired": "Pochta indeksi majburiy.",
    "cart.zipInvalid": "Pochta indeksi formati noto‘g‘ri.",
    "cart.discountRequired": "Chegirma kodini kiriting.",
    "cart.discountMin": "Chegirma kodi kamida 4 ta belgidan iborat bo‘lsin.",
    "checkout.completeDetails": "Buyurtmani yuborishdan oldin yetkazish ma’lumotlaringizni to‘ldiring va buyurtmani tekshiring.",
    "checkout.secure": "Xavfsiz checkout tajribasi",
    "checkout.shippingAddress": "Yetkazish manzili",
    "checkout.useActive": "Siz bilan tez bog‘lanishimiz uchun faol kontakt ma’lumotlaridan foydalaning.",
    "checkout.optional": "Ixtiyoriy",
    "checkout.placeOrder": "Buyurtmani yuborish",
    "checkout.backToCart": "Savatga qaytish",
    "checkout.orderSummary": "Buyurtma xulosasi",
    "checkout.itemsSelected": "{count} ta mahsulot tanlangan",
    "checkout.empty": "Savatingiz bo‘sh",
    "checkout.emptyDesc": "Buyurtma xulosasini ko‘rish uchun mahsulot qo‘shing.",
    "checkout.confirmed": "Buyurtma tasdiqlandi",
    "checkout.confirmedDesc": "Buyurtmangiz qabul qilindi. Tez orada siz bilan bog‘lanamiz.",
    "checkout.confirmedSub": "Biz bilan xarid qilganingiz uchun rahmat. Jamoamiz ma’lumotlaringizni ko‘rib chiqib, keyingi bosqichlar bo‘yicha aloqaga chiqadi.",
    "checkout.continue": "Davom etish",
    "checkout.keepShopping": "Xaridni davom ettirish",
    "checkout.orderReady": "Hammasi joyida. Buyurtmangiz yuborishga tayyor.",
    "checkout.fillRequired": "Buyurtma yuborishdan oldin majburiy maydonlarni to‘ldiring.",
    "checkout.cartEmptyError": "Savatingiz bo‘sh. Buyurtma berishdan oldin mahsulot qo‘shing.",
    "checkout.emailInvalid": "To‘g‘ri email manzil kiriting.",
    "checkout.emailRequired": "Email manzil majburiy.",
    "checkout.firstNameMin": "Ism kamida 2 belgidan iborat bo‘lsin.",
    "checkout.firstNameRequired": "Ism majburiy.",
    "checkout.lastNameMin": "Familiya kamida 2 belgidan iborat bo‘lsin.",
    "checkout.lastNameRequired": "Familiya majburiy.",
    "checkout.streetMin": "Ko‘cha manzili kamida 6 belgidan iborat bo‘lsin.",
    "checkout.streetRequired": "Ko‘cha manzili majburiy.",
    "checkout.cityMin": "Shahar kamida 2 belgidan iborat bo‘lsin.",
    "checkout.cityRequired": "Shahar majburiy.",
    "checkout.stateMin": "Viloyat/Shahar kamida 2 belgidan iborat bo‘lsin.",
    "checkout.stateRequired": "Viloyat/Shahar majburiy.",
    "checkout.zipInvalid": "To‘g‘ri pochta indeksini kiriting.",
    "checkout.zipRequired": "Pochta indeksi majburiy.",
    "checkout.countryRequired": "Mamlakat majburiy.",
    "checkout.phoneInvalid": "To‘g‘ri telefon raqamini kiriting.",
    "checkout.phoneRequired": "Telefon raqami majburiy.",
    "deals.title": "Aksiyalarimiz",
    "deals.desc": "Routing ishlayapti. Bu yerga aksiyalar va promo kartalarni qo‘shing.",
  },
  ru: {
    "common.language": "Язык",
    "common.theme": "Тема",
    "common.light": "Светлая",
    "common.dark": "Тёмная",
    "common.english": "English",
    "common.uzbek": "O‘zbek",
    "common.russian": "Русский",
    "common.home": "Главная",
    "common.cart": "Корзина",
    "common.checkout": "Оформление",
    "common.country": "Страна",
    "common.stateProvince": "Область/Регион",
    "common.zipPostalCode": "Почтовый индекс",
    "common.city": "Город",
    "common.company": "Компания",
    "common.phoneNumber": "Телефон",
    "common.firstName": "Имя",
    "common.lastName": "Фамилия",
    "common.emailAddress": "Email адрес",
    "common.streetAddress": "Адрес",
    "common.apartmentSuite": "Квартира / Офис",
    "common.applyDiscount": "Применить скидку",
    "common.promocode": "Промокод",
    "common.applied": "Применён",
    "common.subtotal": "Сумма",
    "common.shipping": "Доставка",
    "common.tax": "Налог",
    "common.total": "Итого",
    "common.orderTotal": "Общая сумма",
    "common.noImage": "Нет изображения",
    "topBar.days": "Пн–Чт:",
    "topBar.hours": "9:00 - 17:30",
    "topBar.showroom": "Посетите наш шоурум по адресу 1234 Street Address City Address, 1234",
    "topBar.contactUs": "Связаться с нами",
    "topBar.callUs": "Позвоните нам:",
    "nav.laptops": "Ноутбуки",
    "nav.desktopPcs": "Настольные ПК",
    "nav.networkingDevices": "Сетевые устройства",
    "nav.printersScanners": "Принтеры и сканеры",
    "nav.pcParts": "Комплектующие ПК",
    "nav.allOtherProducts": "Другие товары",
    "nav.repairs": "Ремонт",
    "nav.ourDeals": "Акции",
    "hero.deal": "СПЕЦИАЛЬНОЕ ПРЕДЛОЖЕНИЕ",
    "hero.title": "Получите бонусный игровой монитор",
    "hero.subtitle": "При покупке выбранного игрового desktop от MSI",
    "hero.shopNow": "КУПИТЬ СЕЙЧАС",
    "hero.valid": "Действует с 12 мая по 7 сентября 2020 года или пока товар есть в наличии.",
    "hero.worthUp": "Стоимость",
    "hero.worthTo": "до $599AU",
    "hero.processor": "Процессор Intel® Core™ i9",
    "newProducts.title": "Новые товары",
    "newProducts.seeAll": "Все новые товары",
    "product.inStock": "в наличии",
    "product.checkAvailability": "проверить наличие",
    "product.reviews": "Отзывы ({count})",
    "product.noProductsFound": "Товары не найдены",
    "product.supabaseEmpty": "Таблица `products` в Supabase пуста или ещё не подключена.",
    "category.collection": "Коллекция MSI",
    "category.seeAllProducts": "Все товары",
    "category.customBuilds": "Кастомные сборки",
    "category.preBuiltPcs": "Готовые ПК",
    "category.miniItx": "Mini ITX",
    "category.towerCases": "Tower корпуса",
    "category.msiGs": "Серия MSI GS",
    "category.msiGt": "Серия MSI GT",
    "category.msiGl": "Серия MSI GL",
    "category.msiGe": "Серия MSI GE",
    "category.gaming": "Игровые",
    "category.professional": "Профессиональные",
    "category.curved": "Изогнутые",
    "category.ultraWide": "UltraWide",
    "category.msiInfinite": "Серия MSI Infinite",
    "category.msiTrident": "MSI Trident",
    "category.msiNightblade": "MSI Nightblade",
    "instagram.title": "Следите за нами в Instagram: новости, предложения и многое другое",
    "testimonial.leaveReview": "Оставить отзыв",
    "support.productSupport": "Поддержка продукта",
    "support.productSupportDesc": "До 3 лет выездной гарантии для вашего спокойствия.",
    "support.personalAccount": "Персональный аккаунт",
    "support.personalAccountDesc": "Большие скидки, бесплатная доставка и персональный специалист.",
    "support.amazingSavings": "Отличная экономия",
    "support.amazingSavingsDesc": "До 70% скидки на новые товары — лучшая цена гарантирована.",
    "footer.newsletterTitle": "Подпишитесь на нашу рассылку.",
    "footer.newsletterDesc": "Узнавайте о последних предложениях первыми.",
    "footer.yourEmail": "Ваш Email",
    "footer.subscribe": "Подписаться",
    "footer.information": "Информация",
    "footer.address": "Адрес",
    "footer.addressText": "Адрес: 1234 Street Adress City Address, 1234",
    "footer.phones": "Телефоны:",
    "footer.openHours1": "Часы работы: Понедельник-Четверг: 9:00 - 17:30",
    "footer.openHours2": "Пятница: 9:00 - 18:00",
    "footer.openHours3": "Суббота: 11:00 - 17:00",
    "footer.email": "E-mail:",
    "footer.copyright": "Copyright © 2020 Shop Pty. Ltd.",
    "cart.shoppingCart": "Корзина",
    "cart.itemsInCart": "В вашей корзине {count} товар(ов)",
    "cart.continueShopping": "Продолжить покупки",
    "cart.product": "Товар",
    "cart.price": "Цена",
    "cart.qty": "Кол-во",
    "cart.total": "Итого",
    "cart.clear": "Очистить корзину",
    "cart.update": "Обновить корзину",
    "cart.empty": "Ваша корзина пуста",
    "cart.emptyDesc": "Добавьте товар, чтобы увидеть его здесь.",
    "cart.summary": "Сводка",
    "cart.estimateShipping": "Рассчитать доставку и налог",
    "cart.enterDestination": "Введите адрес назначения, чтобы рассчитать доставку.",
    "cart.applyDiscountCode": "Применить код скидки",
    "cart.enterDiscount": "Введите код скидки",
    "cart.proceedCheckout": "Перейти к оформлению",
    "cart.paypal": "Оплатить через PayPal",
    "cart.multipleAddresses": "Оформить на несколько адресов",
    "cart.usePromo": "Используйте промокод:",
    "cart.promoInvalid": "Промокод недействителен. Попробуйте {code}.",
    "cart.promoSuccess": "{code} успешно применён. Теперь вы получаете 50% скидку на общую сумму заказа.",
    "cart.discountRow": "Промо ({code})",
    "cart.addItemBeforeCheckout": "Добавьте хотя бы один товар перед оформлением.",
    "cart.checkoutReady": "Данные готовы. Переходим к оформлению.",
    "cart.fillShippingFirst": "Перед продолжением заполните страну, регион и индекс.",
    "cart.countryRequired": "Выберите страну.",
    "cart.stateRequired": "Заполните поле Область/Регион.",
    "cart.stateMin": "Введите минимум 2 символа.",
    "cart.zipRequired": "Почтовый индекс обязателен.",
    "cart.zipInvalid": "Неверный формат почтового индекса.",
    "cart.discountRequired": "Введите код скидки.",
    "cart.discountMin": "Код скидки должен содержать не менее 4 символов.",
    "checkout.completeDetails": "Заполните данные доставки и проверьте заказ перед оформлением.",
    "checkout.secure": "Безопасное оформление заказа",
    "checkout.shippingAddress": "Адрес доставки",
    "checkout.useActive": "Используйте актуальные контактные данные, чтобы мы могли быстро с вами связаться.",
    "checkout.optional": "Необязательно",
    "checkout.placeOrder": "Оформить заказ",
    "checkout.backToCart": "Вернуться в корзину",
    "checkout.orderSummary": "Сводка заказа",
    "checkout.itemsSelected": "Выбрано {count} товар(ов)",
    "checkout.empty": "Ваша корзина пуста",
    "checkout.emptyDesc": "Добавьте товары, чтобы увидеть сводку заказа.",
    "checkout.confirmed": "Заказ подтверждён",
    "checkout.confirmedDesc": "Ваш заказ принят. Мы скоро с вами свяжемся.",
    "checkout.confirmedSub": "Спасибо за покупку. Наша команда проверит ваши данные и свяжется с вами по следующим шагам.",
    "checkout.continue": "Продолжить",
    "checkout.keepShopping": "Продолжить покупки",
    "checkout.orderReady": "Всё в порядке. Ваш заказ готов к отправке.",
    "checkout.fillRequired": "Пожалуйста, заполните обязательные поля перед оформлением заказа.",
    "checkout.cartEmptyError": "Ваша корзина пуста. Добавьте товары перед оформлением заказа.",
    "checkout.emailInvalid": "Введите корректный email адрес.",
    "checkout.emailRequired": "Email адрес обязателен.",
    "checkout.firstNameMin": "Имя должно содержать минимум 2 символа.",
    "checkout.firstNameRequired": "Имя обязательно.",
    "checkout.lastNameMin": "Фамилия должна содержать минимум 2 символа.",
    "checkout.lastNameRequired": "Фамилия обязательна.",
    "checkout.streetMin": "Адрес должен содержать минимум 6 символов.",
    "checkout.streetRequired": "Адрес обязателен.",
    "checkout.cityMin": "Город должен содержать минимум 2 символа.",
    "checkout.cityRequired": "Город обязателен.",
    "checkout.stateMin": "Регион должен содержать минимум 2 символа.",
    "checkout.stateRequired": "Регион обязателен.",
    "checkout.zipInvalid": "Введите корректный почтовый индекс.",
    "checkout.zipRequired": "Почтовый индекс обязателен.",
    "checkout.countryRequired": "Страна обязательна.",
    "checkout.phoneInvalid": "Введите корректный номер телефона.",
    "checkout.phoneRequired": "Номер телефона обязателен.",
    "deals.title": "Наши акции",
    "deals.desc": "Маршрутизация работает. Добавьте сюда промо-кампании и карточки акций.",
  },
};

const AppPreferencesContext = createContext<AppPreferencesContextValue | null>(null);

function interpolate(template: string, params?: Record<string, string | number>) {
  if (!params) {
    return template;
  }

  return Object.entries(params).reduce((result, [key, value]) => result.replaceAll(`{${key}}`, String(value)), template);
}

export function AppPreferencesProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>("en");
  const [theme, setThemeState] = useState<AppTheme>("light");

  useEffect(() => {
    const savedLanguage = window.localStorage.getItem(STORAGE_LANGUAGE_KEY) as AppLanguage | null;
    const savedTheme = window.localStorage.getItem(STORAGE_THEME_KEY) as AppTheme | null;

    if (savedLanguage === "en" || savedLanguage === "uz" || savedLanguage === "ru") {
      setLanguageState(savedLanguage);
    }

    if (savedTheme === "light" || savedTheme === "dark") {
      setThemeState(savedTheme);
    }
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    window.localStorage.setItem(STORAGE_LANGUAGE_KEY, language);
  }, [language]);

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    window.localStorage.setItem(STORAGE_THEME_KEY, theme);
  }, [theme]);

  const value = useMemo<AppPreferencesContextValue>(
    () => ({
      language,
      setLanguage: setLanguageState,
      theme,
      setTheme: setThemeState,
      toggleTheme: () => setThemeState((current) => (current === "light" ? "dark" : "light")),
      t: (key, params) => interpolate(translations[language][key] ?? translations.en[key] ?? key, params),
    }),
    [language, theme],
  );

  return <AppPreferencesContext.Provider value={value}>{children}</AppPreferencesContext.Provider>;
}

export function useAppPreferences() {
  const context = useContext(AppPreferencesContext);

  if (!context) {
    throw new Error("useAppPreferences must be used within AppPreferencesProvider");
  }

  return context;
}
